### PR TITLE
Automatically discover HMD resolution by parsing EDID.

### PR DESCRIPTION
**Pull request by nsf**
Sorry if the code is a bit trashy, but it should work.

### CODE REVIEW

**Comment by CertainLach** [comment]
Actually i want to implement it other way around: reconfigure headset on SteamVR startup

**Comment by nsf** [comment]
I don't insist this solution stays there forever. But for now, It's a bit better than recompiling things.

**Comment by CertainLach** [comment]
I have implemented automatic reconfiguration here, also no recompilation needed:
https://github.com/CertainLach/VivePro2-Linux-Driver/releases/tag/v0.2.0-rust.1

**Comment by CertainLach** [comment]
Published Rust rewrite source code with dynamic reconfiguration written

**Pull request closed without merging**
